### ISSUE TITLE
Bug when I scale a surface to destSurface

### ISSUE THREAD

**Issue by ExtraMobs** [pygame-community/pygame-ce#2116] opened 2023-04-15 02:56 UTC
The problem is very simple, I have a module for pygame that works with scales, and when I apply the scales, the following error appears:

![image](https://user-images.githubusercontent.com/50765958/232179608-d3af1c48-08ae-419b-b848-6ba2b11d7060.png)

You can see that where the arrows are, is the 'format' of the surface, both are 32, and the error is displayed on the screen.

To clarify, the Display is a surface that I draw to later scale to the Window, which is the surface of the "display" module.

[]
pygame-ce 2.2.1 (SDL 2.26.4, Python 3.10.11)

**Comment by ExtraMobs** [comment] 2023-04-15 02:57
pygame-ce 2.2.1 (SDL 2.26.4, Python 3.10.11)

**Comment by Starbuck5** [comment] 2023-04-15 04:13
Are you reporting this as a regression or a bug?

They may have the same bit depths but they must not have the same format. RGBA vs BGRA perhaps.

Oh... is one of them RGBX and the other is RGBA?

**Comment by ExtraMobs** [comment] 2023-04-15 05:43
I deduced that it was a bug because I thought that pygame only worked with RGBA, but even using .convert() the error continues

**Comment by Starbuck5** [comment] 2023-04-15 06:10
I just want to know if you had this working on a previous version of pygame-ce and then it broke in 2.2.1?

I think if you go back to 2.2.0 your code will work. `pip install pygame-ce==2.2.0`

> I deduced that it was a bug because I thought that pygame only worked with RGBA, but even using .convert() the error continues

Pygame works with many pixel formats.

**Comment by ExtraMobs** [comment] 2023-04-15 06:12
yes, that's what I did, I wanted to be able to try the performance increase of the new algorithm, too bad it didn't work

**Comment by Starbuck5** [comment] 2023-04-15 06:18
> yes, that's what I did

What?

**Comment by ExtraMobs** [comment] 2023-04-15 06:21
![image](https://user-images.githubusercontent.com/50765958/232190244-d8ff7c2f-a1ab-47e6-ae83-a96822620f3a.png)

If it was a translation error, I'm sorry, I use a translator to communicate, but if not, I refer to this

**Comment by Starbuck5** [comment] 2023-04-15 06:22
I just want to know whether this code worked for you on pygame-ce 2.2.0, because I suspect it will.

**Comment by ExtraMobs** [comment] 2023-04-15 06:23
yes it works fine in 2.2.0

**Comment by Starbuck5** [comment] 2023-04-15 06:25
That's the most important part of this issue. I believe I know the exact cause.

What operating system and python version do you use?

**Comment by ExtraMobs** [comment] 2023-04-15 06:26
pygame-ce 2.2.1 (SDL 2.26.4, Python 3.10.11)
Windows 11 x64

**Comment by mmdmoa** [comment] 2023-05-06 19:49
[https://github.com/II-ZEN-II/Pygame-Jam-2023/commit/9b2058637853d573b0acbb80c5cf7ad9107e76ea](https://github.com/II-ZEN-II/Pygame-Jam-2023/commit/9b2058637853d573b0acbb80c5cf7ad9107e76ea)

I stumbled upon a similar problem in this project.
I can send some logs and system info if it's needed

**Comment by Starbuck5** [comment] 2023-05-27 23:57
Following up a bit. Last week I opened a PR to fix this issue, so hopefully that should be merged and in by the next pygame-ce release.

**Closed** 2023-05-28 02:18 UTC
Labels: bug, transform
