### ISSUE TITLE
Window flickers while resizing (3125)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1581] opened 2023-02-12 16:27 UTC
#  **Issue &numero;3125 opened by *[gresm](https://github.com/gresm)* at 2022-04-07 20:32:50**

(Reported by @hl037 )
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux(Ubuntu)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.4
- **SDL version** (e.g. SDL 2.0.12): 2.0.16
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2

**Current behavior:**

When resizing the window, the surface is completely cleared and the program can't replace it before the new, black surface will be send to operating system, resulting flickering.

**Expected behavior:**

When resizing, it should not be called to update the screen, or at leas blit the older surface onto new one.

**Test code**

Provided by @MyreMylar 

```python
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480), pygame.RESIZABLE)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

small_size = True

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.WINDOWRESIZED:
            white_background = pygame.Surface(screen.get_rect().size)
            white_background.fill((255, 255, 255))
         
    screen.blit(white_background, (0, 0))
    pygame.display.flip()


pygame.quit()
```
<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-04-17 00:23:09*

I don't see it on Windows.

I'm assuming it happens on pygame from pip. It seems like most "Linux weirdness" can be solved by building pygame locally, so you could give that a shot.
<hr>

# # #  **[bydariogamer](https://github.com/bydariogamer)* commented at 2022-04-22 07:03:08*

I was unable to reproduce this code in python 3.10.4 compiled with GCC 11.2.0 on an Arch Linux with GNOME 42.0 desktop using pygame 2.1.2 and SDL 2.0.16

**Comment by ankith26** [comment] 2023-12-16 18:58
Also on Ubuntu (but 23.10) and `pygame-ce 2.3.2 (SDL 2.26.5, Python 3.11.6)`, cannot reproduce this issue, so I'm closing. Feel free to comment with new info if this issue is still persisting and I will re-open this issue

**Closed by ankith26** 2023-12-16 18:58 UTC
Labels: bug, display
