### ISSUE TITLE
smoothscale crashes Python on Raspberry Pi 4 (2086)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1104] opened 2023-02-12 13:21 UTC
#  **Issue &numero;2086 opened by *[project-owner](https://github.com/project-owner)* at 2020-09-09 16:30:17**

The following code works fine on Raspberry Pi 3:
```
pygame.transform.smoothscale(image, ratio, s)
```
but it crashes Python on Raspberry Pi 4. Python 3.7.3, pygame 1.9.4.post1

The following code can be used as a workaround but it produces not so good images:
```
img = pygame.transform.scale(image, ratio)
s.blit(img, (0,0))
```
Here is another workaround using Image class from the Pillow library:
```
d = pygame.image.tostring(image, "RGBA", False)
img = Image.frombytes("RGBA", image.get_size(), d)
i = img.resize(ratio)
d = pygame.image.fromstring(i.tobytes(), i.size, i.mode)
s.blit(d, (0, 0))
```

Here is the whole function:
https://github.com/project-owner/Peppy/blob/4c237558feee1dd5dc602cf48af2d5b7e9b86724/util/imageutil.py# L244
<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-09-10 11:00:44*

1.9.4 is a rather old version of pygame now, I would try 1.9.6 first to see if that fixes your issue, and if not see if you can get 2.0.0.dev10 running on there. There are some SDL2 issues with Pi but I don't think they were smooth scale related.
<hr>

# # #  **[project-owner](https://github.com/project-owner)* commented at 2020-09-11 03:37:05*

Right now 1.9.4 is the default version when you install Pygame on Raspberry Pi without specifying the version explicitly:
sudo apt-get install python3-pygame
I installed 1.9.6:
pip3 install pygame==1.9.6
But it has the same problem with smoothscale on Pi 4.
At the moment I cannot switch to Pygame 2 because of this issue:
https://github.com/pygame/pygame/issues/1187
<hr>

# # #  **[MightyJosip](https://github.com/MightyJosip)* commented at 2020-09-11 08:57:40*

You can install pygame2, try to scale the image and see if it works and then return back to 1.9
<hr>

# # #  **[project-owner](https://github.com/project-owner)* commented at 2020-09-12 17:32:12*

I've tried to switch to Pygame 2 and commented out CD support in my program but then faced some font issues. So I'll use the PIL workaround for now as I'm using that library for blurring anyway.

BTW, the issue occurs only with the Official Raspberry Pi 7" Touchscreen. I tested with 3.5" display and didn't see the smoothscale issue.
<hr>

# # #  **[illume](https://github.com/illume)* commented at 2020-09-13 08:21:32*

> BTW, the issue occurs only with the Official Raspberry Pi 7" Touchscreen. I tested with 3.5" display and didn't see the smoothscale issue.

That's a good hint. I wonder what the attributes of the 7" Touchscreen are?
```python
s = pygame.display.get_surface();print(s.get_losses(), s.get_shifts(), s.get_flags(), s.get_pitch())
```
<hr>

# # #  **[project-owner](https://github.com/project-owner)* commented at 2020-09-13 17:23:07*

Here is the output:
(3, 2, 3, 8)
(11, 5, 0, 0)
32
1600
The display resolution is 800x480
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2021-11-20 16:47:01*

I wonder whether this issue still happens on pygame 2.1, if not this issue can be closed. I can't seem to reproduce on a pi3 (but I don't have the Official Raspberry Pi 7" Touchscreen that OP reports the problem on)

**Comment by Starbuck5** [comment] 2023-09-17 20:03
I asked Kyuchumimo on discord to test this on their raspberry pi, they couldn't reproduce the bug.

**Comment by Starbuck5** [comment] 2023-09-17 20:21
Ok looking more at the info provided I see that @project-owner is using a 16 bit surface (maybe that's what their display defaults to). In the smoothscale docs, it states you can only use 24 or 32 bit surfaces in smoothscale.

```
>>> import pygame
pygame-ce 2.4.0.dev1 (SDL 2.26.5, Python 3.9.5)
>>> s = pygame.Surface((32,32), depth=16)
>>> s.get_shifts()
(11, 5, 0, 0)
>>> s.get_losses()
(3, 2, 3, 8)
>>> s.get_flags()
0
>>> s.get_pitch()
64
>>> pygame.transform.smoothscale(s, (64,64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Only 24-bit or 32-bit surfaces can be smoothly scaled
```

Since OP never gave a traceback I think all the maintainers assumed it was segfaulting, when really the issue was in the error message the entire time.

**Comment by MyreMylar** [comment] 2023-09-30 12:25
Closing as the explanation above seems plausible and we are unlikely to get an update now.

**Closed by MyreMylar** 2023-09-30 12:25 UTC
Labels: transform
