### ISSUE TITLE
No way to draw filled aaellipse (354)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#364] opened 2023-02-12 08:22 UTC
# **Issue &numero;354 opened by *[kjyv](https://github.com/kjyv)* at 2017-09-11 15:49:23**

While the pygame.draw.ellipse() method has a flag to draw it filled, there is no such flag for the pygame.gfxdraw.aaellipse() method. First drawing a gfxdraw.filled_ellipse() (without anti-aliasing), then drawing an aaellipse() does not produce good results. The same situation exists for aapolygon, but there drawing a filled_polygon() first works well enough, apart from probably being less efficient.

**Related Docs:** https://www.pygame.org/docs/ref/gfxdraw.html#pygame.gfxdraw.aaellipse<hr>

# Comments

**Comment by zoldalma999** [comment] 2023-07-23 21:15
Duplicate of #671

**Closed by zoldalma999** 2023-07-23 21:15 UTC
Labels: enhancement, draw, gfxdraw
