### ISSUE TITLE
Segmentation fault (core dumped) when executing pygame.mixer.Sound.play() a second time. (3468)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1717] opened 2023-02-12 17:24 UTC
#  **Issue &numero;3468 opened by *[MichaelTennant](https://github.com/MichaelTennant)* at 2022-09-28 18:23:04**

**Environment:**

- **Operating system** Linux Debian Mint
- **Python version** 3.6.9
- **PyGame version** 2.1.2

**Current behavior:**

Program exits due to signal `SIGSEGV` being sent resulting in the error code `Segmentation fault (core dumped)` occasionally when `pygame.mixer.Sound().play()`. The error usually occurs the second time `pygame.mixer.Sound().play()` is executed in the program. The error cannot be caught by a try except block.

Link to the project files [here](https://github.com/MichaelTennant/TheFakeNewsGame/tree/Linux).

Edit: In the simplified code [below](https://github.com/pygame/pygame/issues/3468# issuecomment-1263601828) I have managed to replicate the issue except this time the program crashes the first time `pygame.mixer.Sound().play()` is sent.<hr>

#  Comments

# # #  **[MichaelTennant](https://github.com/MichaelTennant)* commented at 2022-09-29 13:28:31*

The issue can be fixed by stopping the sound with `pygame.mixer.Sound().stop()` before playing the sound again.
<hr>

# # #  **[novialriptide](https://github.com/novialriptide)* commented at 2022-09-30 02:12:53*

This should remain open as the source of the segmentation fault is from pygame.
<hr>

# # #  **[novialriptide](https://github.com/novialriptide)* commented at 2022-09-30 05:13:31*

Could you also post a simplified version of the code here? I'm trying to reproduce this issue but I'm unable to do so.
<hr>

# # #  **[MichaelTennant](https://github.com/MichaelTennant)* commented at 2022-09-30 13:49:35*

> Could you also post a simplified version of the code here? I'm trying to reproduce this issue but I'm unable to do so.

@novialriptide I have managed to consistently get the error to occur on my device with the following code:

```
# !/bin/env python3
import pygame

pygame.init()
pygame.mixer.init()

pygame.display.set_mode((640, 480))
sound = pygame.mixer.Sound("./ShortSoundFile.wav")

while True:
    for event in pygame.event.get():
        if event.type == pygame.KEYDOWN:
            sound.play()
```

Any .wav sound file should work, I haven't tested for other file types. To trigger the bug press any key while the window is highlighted once, I couldn't seem simplify the code any further than this. For some strange reason the SIGSEGV signal is sent after the first time sound.play() is executed in this scenario.
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-10-05 09:53:19*

Hello!

I'm unable to reproduce this issue on windows 11 and Ubuntu 22.04 (python 3.10, pygame 2.1.2)
For me, all sounds just play simultaneously (as expected)

Perhaps this issue is file specific, can you attach the file that reproduces this issue for you? Alternatively, it could also be a python 3.6 only bug (if possible, can you test with another python version?)
<hr>

# # #  **[MichaelTennant](https://github.com/MichaelTennant)* commented at 2022-10-05 15:08:23*

> Hello!
> 
> I'm unable to reproduce this issue on windows 11 and Ubuntu 22.04 (python 3.10, pygame 2.1.2) For me, all sounds just play simultaneously (as expected)
> 
> Perhaps this issue is file specific, can you attach the file that reproduces this issue for you? Alternatively, it could also be a python 3.6 only bug (if possible, can you test with another python version?)

The Issue seems to only occur on python 3.6 as the issue does not occur in python 3.10
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-10-05 15:21:31*

Hmmm... I can't reproduce the issue locally on windows 3.6 either

**Comment by Isoheptane** [comment] 2023-06-15 13:53
I'm also unable to reproduce this issue on Arch Linux (Python 3.11.3, pygame-ce 2.3.0).
Test code is basically the same as MichaelTennant's code:
```
import pygame

pygame.init()
pygame.mixer.init()

pygame.display.set_mode((640, 480))
sound = pygame.mixer.Sound("./test.wav")


while True:
    for event in pygame.event.get():
        if event.type == pygame.KEYDOWN:
            sound.play()
```

**Comment by MyreMylar** [comment] 2023-09-30 12:42
This bug was Python 3.6 only. We no longer support python 3.6 in pygame-ce so closing.

**Closed by MyreMylar** 2023-09-30 12:42 UTC
Labels: bug, mixer, Python 3.6
