### ISSUE TITLE
pygame.mixer.music endevent triggered by set_volume

### ISSUE THREAD

**Issue by scribblecrumb** [pygame-community/pygame-ce#2797] opened 2024-04-10 11:19 UTC
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows
- **Python version** (e.g. 3.11.1, 3.8.5) : Python 3.11.2
- **SDL version** (e.g. SDL 2.0.12): SDL 2.26.4
- **pygame-ce version** (e.g. 2.4.0.dev4, 2.1.3): pygame-ce 2.2.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

I set up a custom event to be triggered when the music ends via set_endevent. 
```
MUSIC_END = pygame.USEREVENT + 1
pygame.mixer.music.set_endevent(MUSIC_END)
```
I found that the MUSIC_END event was being triggered both when the music ends and when `pygame.mixer.music.set_volume` is used.

**Expected behavior:**

I would expect for the endevent to only trigger when the music ends.

**Screenshots**

N/A

**Steps to reproduce:**

1. Create a custom event using `pygame.USEREVENT`
2. Set that event to queue when the music ends via `pygame.mixer.music.set_endevent()`
3. Change the volume of the music using `pygame.mixer.music.set_volume()`

**Test code**
N/A (i'll add one if i find time later to write one up)

**Stack trace/error output/other error logs**
N/A

**Comment by ankith26** [comment] 2024-04-14 04:29
Hello!

I cannot reproduce this issue. I'm on Ubuntu 23.10 and using `pygame-ce 2.4.1 (SDL 2.28.5, Python 3.11.6)`.

I tested with the `music_drop_fade` example that comes along with the pygame-ce install.

Please provide a minimal reproducer that triggers the bug for you, more factors other than calling `set_volume` may be involved in order to trigger this bug.

**Comment by ankith26** [comment] 2024-05-12 12:19
```py
import random
import pygame

MYEVENT = pygame.USEREVENT + 1


class App:
    def __init__(self) -> None:
        pygame.init()
        self.display = pygame.display.set_mode([320, 180])
        path = "sample.mp3"
        pygame.mixer.music.load(path)
        pygame.mixer.music.play()
        pygame.mixer.music.set_endevent(MYEVENT)

    def check_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                exit()
            if event.type == pygame.KEYDOWN:
                pygame.mixer.music.set_volume(random.randint(0, 100) / 100)
            if event.type == MYEVENT:
                print("myevent")

    def update(self): ...

    def render(self):
        self.display.fill("white")
        pygame.display.flip()

    def run(self):
        while True:
            self.check_events()
            self.update()
            self.render()


if __name__ == "__main__":
    a = App()
    a.run()
```

Here is another sample I tested with (thanks to @pycoinfu for providing this) and I still cannot reproduce the issue. I am closing this issue for now, but feel free to re-open if you can write a similar script that reproduces the issue for you.

**Closed by ankith26** 2024-05-12 12:19 UTC
Labels: bug
