### ISSUE TITLE
`pygame.Surface.fblits` slower in 2.5.0.dev2 vs 2.4.1

### ISSUE THREAD

**Issue by oddbookworm** [pygame-community/pygame-ce#2821] opened 2024-04-26 03:01 UTC
@bigwhoopgames mentioned on discord that he's getting a 25%-33% fps drop when using the 2.5.0.dev2 prerelease vs the 2.4.1 release. I did some testing by giving him special wheels with specific changes to see if that fixed it, but didn't really see much difference. List of things I tried:
* Reverting #2679
* Reverting #2679 and #2667
* Adding `/Ox` to the MSVC build in meson
* Setting `optimization` to `3` in meson

Image provided by Big Whoop showing some comparisons from a performance profile
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/289b9d4d-dbbc-4b7b-9e62-89d5781ccb73)

**Comment by bigwhoopgames** [comment] 2024-04-26 17:03
Tested with my youtube particles tutorial. Running on 2.4.1 ~20K particles at 60FPS and on 2.5.0 getting about 6800.

https://github.com/bigwhoopgames/youtube-particles/blob/master/particles.py

Line 88 needs changing to work with python 3.12, just wrap values passed to random as ints.

**Comment by itzpr3d4t0r** [comment] 2024-04-26 17:05
Could it be SDL's fault? We got `SDL 2.28.5` on `2.4.1` and `SDL 2.30.2` on `2.5.0 -dev2`. It's basically the only thing that changed between our releases with fblits.

**Comment by itzpr3d4t0r** [comment] 2024-04-26 17:17
Confirmed, i tested installing the latest pygame-ce version with SDL 2.28.5 and the fps in my test program are back to pygam.ce 2.4.1 territory. (got 400 fps in 2.4.1 and 260-270 in 2.5.0 dev2 and 350-400 with 2.5.0 with the old SDL version)

**Comment by oddbookworm** [comment] 2024-04-26 17:35
How hard would making an SDL reproducer be so I can report it upstream to them?

**Comment by robertpfeiffer** [comment] 2024-04-26 18:17
Do you even need to recompile?
Just compile with SDL SDL 2.28.5 and substitute with 2.30.2 through the dynamic API replacer

SDL3_DYNAMIC_API=/my/actual/libSDL2.so.30.2 python3 benchmark.py

**Comment by Starbuck5** [comment] 2024-04-29 06:31
Information from discord-

itzpr said
> To be specific I restricted the issue between 2.28.5 and 2.29.3
Couldn't really install 2.29.1 but i guess 2.29.0 introduced the issue

oddbookworm posted a C reproducer attempt
```c
#include <stdio.h>
#include <sys/time.h>

#define SDL_MAIN_HANDLED
#include "SDL2/SDL.h"

long long timeInMilliseconds(void) {
    struct timeval tv;

    gettimeofday(&tv,NULL);
    return (((long long)tv.tv_sec)*1000)+(tv.tv_usec/1000);
}

Uint32 ColorToUint(int R, int G, int B)
{
    return (Uint32)((R << 16) + (G << 8) + (B << 0));
}

void blitManyTimes(SDL_Surface* target, SDL_Surface* surf, SDL_Rect* rect, size_t iterations)
{
    for (size_t i = 0U; i < iterations; ++i)
    {
        if (SDL_BlitSurface(surf, rect, target, rect) < 0)
        {
            printf("Failed to perform blit\n");
            return;
        }
    }
}

int main()
{
    printf("SDL %d.%d.%d\n", SDL_MAJOR_VERSION, SDL_MINOR_VERSION, SDL_PATCHLEVEL);

    if (SDL_Init(SDL_INIT_VIDEO) < 0)
    {
        printf("Failed to initialize SDL2\n");
        return -1;
    }

    SDL_Window* window = SDL_CreateWindow("SDL2 Window", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 680, 480, 0);

    if (!window)
    {
        printf("Failed to create window\n");
        return -1;
    }

    SDL_Surface* windowSurface = SDL_GetWindowSurface(window);

    if (!windowSurface)
    {
        printf("Failed to get surface from window");
        return -1;
    }

    SDL_Surface* surf = SDL_CreateRGBSurface(0, 100, 100, 32, 0, 0, 0, 0);
    if (!surf)
    {
        printf("Failed to create surface");
        return -1;
    }

    SDL_Rect rect = { .x = 0, .y = 0, .w = 100, .h = 100 };
    SDL_Color color = { .r = 255, .g = 0, .b = 0, .a = 255 };

    if (SDL_FillRect(surf, &rect, ColorToUint(color.r, color.g, color.b)) < 0)
    {
        printf("Failed to fill surface");
        return -1;
    }

    long long start = timeInMilliseconds();
    blitManyTimes(windowSurface, surf, &rect, 1000000);
    long long end = timeInMilliseconds();

    printf("Total time elapsed: %ld milliseconds\n", end - start);

    return 0;
}
```

He said he didn't see any difference until he switched 100x100 surfs to 10x20.

**Comment by Starbuck5** [comment] 2024-04-29 08:02
Here is a more isolated Python reproducer of the issue. Still using fblits, but I expect this would have the same effect if running a for loop of blits in Python, just harder to spot since that loop would have more overhead.

```py
import random
import time

import pygame

random.seed(36)

width = 600
height = 400

screen = pygame.Surface((width, height))

def make_particle():
    p_surf = pygame.Surface((5,5))
    p_surf.fill((random.randint(0,255), random.randint(0,255), random.randint(0,255)))

    return (p_surf, (random.randint(0, width), random.randint(0, height)))

particles = [make_particle() for _ in range(1000000)]

start = time.time()
screen.fblits(particles)
print(time.time() - start)
```

Previously this runs in like a quarter second, now it runs in about a second.

I tracked it down to between SDL 2.29.2 and 2.29.3

**Comment by itzpr3d4t0r** [comment] 2024-05-01 12:52
Ran a test that runs fblits on 100 positions on increasingly bigger surfaces and confirmed my suspect that this fblits/blitting got slower only with "smaller" surfaces, kinda confirming my idea that it has to do with rect clipping or something rather than the actual blit routine:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/0bbda926-5d35-4178-85bd-10da12d9ff09)

**Comment by Starbuck5** [comment] 2024-05-02 08:36
I bisected the performance regression to https://github.com/libsdl-org/SDL/commit/a6d5c1fe05d0f830d687296bbc4d002984cdec05 (surprisingly, nothing about blitting in there... I guess this makes a logging function more expensive and that something in blit calls it)

We still need a clear C reproducer and to report this to SDL, I'd appreciate someone doing.

**Comment by itzpr3d4t0r** [comment] 2024-05-02 15:53
Ran some tests by removing parts of `pgSurface_Blit`'s if statements (here https://github.com/pygame-community/pygame-ce/blob/7d73fc8f2750146500129c6bcf8b775449a8cf79/src_c/surface.c#L3816-L3953) and I'm pretty sure `SDL_GetColorKey` is the issue, don't know why but removing both `SDL_GetColorKey` calls there brings back 2.4.1 performance.

**Comment by Starbuck5** [comment] 2024-05-03 05:39
Nice find!

Okay, I think I have the full picture now.

We call `SDL_GetColorKey(src, &key)`, but only to check whether the surface has a colorkey or not.

```c
int SDL_GetColorKey(SDL_Surface *surface, Uint32 *key)
{
    if (!surface) {
        return SDL_InvalidParamError("surface");
    }

    if (!(surface->map->info.flags & SDL_COPY_COLORKEY)) {
        return SDL_SetError("Surface doesn't have a colorkey");
    }

    if (key) {
        *key = surface->map->info.colorkey;
    }
    return 0;
}
```

Inside SDL, it calls SDL_SetError if the surface doesn't have a colorkey. But https://github.com/libsdl-org/SDL/commit/a6d5c1fe05d0f830d687296bbc4d002984cdec05 makes that way more expensive because it needs to check the environment for that variable now?

I confirmed the slowdown is coming from GetColorKey rather than rearranging the blit code paths by adding a bunch of them into the function like so:

```c
int res = SDL_GetColorKey(src, &key);
int res2 = SDL_GetColorKey(src, &key);
int res3 = SDL_GetColorKey(src, &key);
int res4 = SDL_GetColorKey(src, &key);
int res5 = SDL_GetColorKey(src, &key);
```

Luckily, there is a newer function called `SDL_HasColorKey`, which is available in SDL 2.0.9 and later. We support SDL 2.0.10 and above right now, so that works. There are several places in our code where we use GetColorKey == 0 that we could easily replace with HasColorKey. However, there are also places where GetColorKey == 0 is tested and the returned color key is actually used, so those blocks will be slightly less efficient than before if replaced with HasColorKey + GetColorKey (two functions instead of one)

**Comment by robertpfeiffer** [comment] 2024-05-03 06:16
That reminds me: I should post the result of my investigation into palettes and the bug on Android.

A palette can have the same colour twice, and if you load a paletted PNG where one colour has alpha transparency and the others do not, then SDL_image will just use the index of that colour as the colour key. This way, the loaded palette can have the same colour twice, with the same RGB values, and both time with an alpha of 255, even though the saved PNG had unique colours in the palette.

We should probably expost SDL_GetColorKey (to get the mapped value of the colour key) and SDL_HasColorKey to Python.

**Comment by Starbuck5** [comment] 2024-05-03 06:26
I just opened #2835 that starts to deal with this. There are other uses of SDL_GetColorKey in our code that need to be retrofitted, but the change made in 2835 is the most critical one and also the simplest, so I hope it's easy to review.

**Comment by ankith26** [comment] 2024-05-07 11:20
If this is not fixed on the SDL side, we could just add something like the following and use it across our codebase when we don't care about the SDL error
```c
int PG_GetColorKey(SDL_Surface *surface, Uint32 *key) {
    if (!SDL_HasColorKey(surface)) {
        return -1;
    }
    return SDL_GetColorKey(surface, key);
}
```

**Closed** 2024-05-08 14:04 UTC
Labels: Performance, Surface, needs testing
