### ISSUE TITLE
Mac - After creating a window using `display.set_mode()`, cannot use `display.set_mode()` again to change to SCALED

### ISSUE THREAD

**Issue by rethanon** [pygame-community/pygame-ce#2376] opened 2023-08-02 19:20 UTC
**Environment:**
- Operating system:  macOS Monterey 12.6.8
- Hardware:  MacBook Pro (early 2015)
- Processer:  2.7GHz Dual Core Intel Core i5
- Python version:  3.11.4
- SDL version:  SDL 2.26.5
- pygame-ce version:  2.3.1.dev4 (also reproduced on 2.3.0 and 2.3.1.dev2)

**Bug behaviour:**
When initializing a window using `display.set_mode()` and NOT using the SCALED flag, if you later attempt to use `display.set_mode()` again to change the window to be SCALED it fails with a pygame error.

**Expected behavior:**
Calling `display.set_mode()` again using SCALED should result in the window being resized with appropriate scale. 

**Screenshots**
![image](https://github.com/pygame-community/pygame-ce/assets/54457966/0f949218-0be0-42a6-8c46-21c91db7fc77)

**Steps to reproduce:**
1. create a window that is not SCALED using the standard set_mode method (i.e. `pygame.display.set_mode((width, height))`)
2. use set_mode again to change the display to be SCALED (i.e. `pygame.display.set_mode((width, height), pygame.SCALED)`)

**Test code:**
Pressing the 1 key re-sets the window, pressing 2 key crashes the program instead of producing a SCALED window.

```
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 600))

run = True
while run:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False
            break
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_1:
                screen = pygame.display.set_mode((800, 600))
            elif event.key == pygame.K_2:
                screen = pygame.display.set_mode((800, 600), pygame.SCALED)
    screen.fill("blue")
    pygame.display.flip()

pygame.quit()
```

**Error details:**
pygame.error: failed to create renderer

**Notes:**
I have tested the code on my Windows 11 machine and it works fine with the same Python and pygame-ce version.
Also, if the window is created with the SCALED flag, using `display.set_mode()` again without the SCALED flag correctly resizes to the window size specified. However, the same issue occurs after this, where an error is seen if you try to change back to SCALED again.

**Comment by Starbuck5** [comment] 2023-08-05 05:43
This is totally expected with all the renderer/surface stuff we've been dealing with. See https://github.com/pygame-community/pygame-ce/issues/2190.

However I'm leaving this open because it is not a duplicate of that, although the problem has the same cause, this is a different manifestation of the problem and should be tracked separately.

**Comment by rethanon** [comment] 2023-08-05 09:22
Thanks @Starbuck5 I knew about the other issue but didn’t realise it was related as that one is specifically referring to `pygame._sdl2`. At least for the other issue there’s a workaround, this one I run into frequently as I work on the same code using both a Windows desktop PC and a MacBook.

**Closed** 2024-07-08 14:21 UTC
Labels: bug, macOS, display
