### ISSUE TITLE
Segmentation fault in cam.start() with HD Pro Webcam C920 (3507)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1731] opened 2023-02-12 17:27 UTC
#  **Issue &numero;3507 opened by *[727854320](https://github.com/727854320)* at 2022-10-20 03:20:55**

`pygame 2.1.2 (SDL 2.0.18, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
['HD Pro Webcam C920']
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized`

Replacement versions, uninstallation and reinstallation did not solve the problem<hr>

#  Comments

# # #  **[oddbookworm](https://github.com/oddbookworm)* commented at 2022-10-20 15:12:12*

It would be helpful if you provided a minimal amount of code that reproduces the issue
<hr>

# # #  **[MightyJosip](https://github.com/MightyJosip)* commented at 2022-10-21 13:06:28*

OS? Camera backend?

Because I have that same camera and I wasn't able to reproduce segfault on 2.1.2
<hr>

# # #  **[727854320](https://github.com/727854320)* commented at 2022-11-11 01:13:11*

``import` pygame

import sys

import pygame.camera as camera

from pygame.locals import *
import time

pygame.init()
pygame.camera.init()
camera.init()
camera_id_list = pygame.camera.list_cameras()
print(camera_id_list)
screen = pygame.display.set_mode((640, 480))

cam = pygame.camera.Camera(camera_id_list[0], (640, 480))
cam.start()
while 1:
    image = cam.get_image()
    screen.blit(image, (0, 0))
    pygame.display.update()
    for event in pygame.event.get():
        if event.type == QUIT:
            sys.exit()
`#  pygame.quit()`
`#  sys.exit()``

**Comment by zoldalma999** [comment] 2023-09-30 14:31
I think I'll close this as there is not enough information to really test what the issue is. I did change the title in hopes of more people finding it this way, if they have the same issue. Feel free to comment if you can reproduce this, with more information.

**Closed by zoldalma999** 2023-09-30 14:31 UTC
Labels: bug
