### ISSUE TITLE
windows msys2 (2754)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1416] opened 2023-02-12 15:24 UTC
#  **Issue &numero;2754 opened by *[illume](https://github.com/illume)* at 2021-10-07 14:02:39**

The PR https://github.com/pygame/pygame/pull/2592 by @dciabrin already added support for building pygame with windows and msys2 (https://www.msys2.org/) here is a place to log anything people find when trying it out, and to continue the discussion.

- [ ] documentation on the wiki (https://www.pygame.org/wiki/CompileWindows). A new section on there, or perhaps its own CompilationMsys2 wiki page. 
- [ ] a github action/workflow to test it still works

<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2021-10-09 07:23:25*

Seems the gh windows workers sometimes have msys2 installed(and even different windows compilers). As seen in # 2741 windows build failures.

**Comment by zoldalma999** [comment] 2023-10-01 17:24
duplicate of #1590

**Closed by zoldalma999** 2023-10-01 17:24 UTC
Labels: Windows
