### ISSUE TITLE
x11 port forwarding not working (2446)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1251] opened 2023-02-12 14:21 UTC
#  **Issue &numero;2446 opened by *[Naohiro2g](https://github.com/Naohiro2g)* at 2021-01-12 00:16:38**

In ssh connection from macOS to raspberry pi, I can open pygame 1.9.6 window on my Mac, but not pygame 2.x.
Why not??  Please tell me what I am missing.

```
$ python3 -m pygame.examples.aliens
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  98
  Current serial number in output stream:  97
```<hr>

#  Comments

# # #  **[Naohiro2g](https://github.com/Naohiro2g)* commented at 2021-01-12 05:14:15*

uum, it seems there are problems around X11 and GL driver on my Mac.
https://unix.stackexchange.com/questions/429760/opengl-rendering-with-x11-forwarding
<hr>

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2021-01-12 14:50:50*

Recent versions of MacOS don't support many OpenGL features any more. What version are you on? I don't know how SDL interacts with XQuartz anyway, but without the versions of mac os and XQuartz (or whatever X Server you used) it is impossible to tell what is going on.
<hr>

# # #  **[Naohiro2g](https://github.com/Naohiro2g)* commented at 2021-01-13 12:28:39*

Hi, thanks for the response.

macOS Mojave 19.14.6
XQuartz.app ver.2.7.11 as X Window System
sdl2 2.0.14_1

Wow, I've just found the XQuartz is going to be 2.8.0 after almost 5 years from the latest 2.7.11.
https://www.xquartz.org/releases/XQuartz-2.8.0_alpha3.html

XQuartz 2.8 might do something better. I'll test it later.

Result of the pygame test:

$ python3 -m pygame.tests
pygame 2.0.1 (SDL 2.0.14, Python 3.7.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
skipping pygame.tests.cdrom_test (tag 'interactive')
skipping pygame.tests.overlay_test (tag 'SDL2_ignore')
skipping pygame.tests.scrap_test (tag 'SDL2_ignore')
:
:
FAIL: test_get_fonts (pygame.tests.font_test.FontModuleTest)
ERROR: test_freetype_SysFont_name (pygame.tests.freetype_test.FreeTypeFontTest)
FAIL: test_get_fonts (pygame.tests.ftfont_test.FtFontModuleTest)
FAIL: test_get_focused (pygame.tests.key_test.KeyModuleTest)
----------------------------------------------------------------------
Ran 1657 tests in 127.417s
FAILED (failures=3, errors=1)
<hr>

# # #  **[robertpfeiffer](https://github.com/robertpfeiffer)* commented at 2021-01-30 16:47:06*

Maybe this will help: https://www.mail-archive.com/xquartz-dev@lists.macosforge.org/msg01027.html
<hr>

# # #  **[Naohiro2g](https://github.com/Naohiro2g)* commented at 2021-01-30 20:43:19*

Thank you1  I'll check it and get back here.
The alpha was worse and I couldn't even launch the app.

**Comment by bilhox** [comment] 2024-10-06 11:35
I'm closing this since it didn't have any activity since almost 4 years.
I'm pinging you @Naohiro2g since you still seem active on github, if you still have the possibility to reproduce it with the newest version of pygame-ce, I'll be reopening this issue.

Also pinging @robertpfeiffer as you participated in this issue.

**Closed by bilhox** 2024-10-06 11:35 UTC
Labels: macOS, opengl, Gnu/Linux
