### ISSUE TITLE
Pygame not detecting duplicate keyboard input events (3670)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1805] opened 2023-02-12 17:40 UTC
#  **Issue &numero;3670 opened by *[Tollund](https://github.com/Tollund)* at 2023-01-13 12:13:10**

**Environment:**

- **Operating system** : Raspberry Pi OS
- **Python version** : 3.9.2
- **SDL version** : 2.0.14
- **PyGame version** : 2.1.2

**Current behavior:**

We're building a hardware device using a raspberry pi with a barcode scanner and a display. The barcode scanner functions like a USB keyboard, and sends keystrokes in quick succession after scanning a barcode. We're having a problem with pygame not detecting duplicate keys from the scanner in quick succession. When running the below code, pygame often misses duplicate keys. 

**Expected behavior:**

Pygame should detect all keyboard input correctly.

**Test Code**

```
import sys, pygame
pygame.init()
screen = pygame.display.set_mode((800, 400))
ID = ""
font = pygame.font.SysFont("Arial", 70)
while True:
        text = font.render("testtext", True, (255, 255, 255), (0, 0, 0))
        textRect = text.get_rect()
        textRect.center = (screen.get_width() // 2, screen.get_height() // 2)
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.KEYDOWN:
                key = pygame.key.name(event.key)
                if key.isdigit():
                    ID += key
                elif key == "return":
                    print(ID)
                    ID = ""
                elif key == "left":
                    pygame.quit()
                    sys.exit()
        screen.fill((0, 0, 0))
        screen.blit(text, textRect)
        pygame.display.flip()
```

Output from scanning the same barcode using the above code:

```
5770857738
5770857738
570857738
577085738
57085738
5770857738
577085738
5770857738
5770857738
5770857738
5770857738
577085738
5770857738
570857738
5770857738
```

When I comment out the last three lines (not updating the screen), the barcode is scanned successfully every time.<hr>

#  Comments

# # #  **[Tollund](https://github.com/Tollund)* commented at 2023-01-13 12:16:58*

From testing it looks like there is about 3-4 miliseconds between each keypress emitted by the scanner.

**Comment by MyreMylar** [comment] 2023-09-30 12:37
I suspect the answer here is to use the `TEXTINPUT` event type and the `.text` attribute to get the entered text.

Weirdly I actually have a barcode scanner on my desk at work so if I remember I will test this program and an alternative using TEXTINPUT to see if it makes a difference.

**Comment by MyreMylar** [comment] 2023-10-30 19:40
I tried using the corrected code (the proper way to gather inputted text) below and could not reproduce this:

```
import pygame
import sys

# tested using Tera 711 barcode scanner

pygame.init()
screen = pygame.display.set_mode((800, 400))
ID = ""
font = pygame.font.SysFont("Arial", 70)
while True:
    text = font.render("testtext", True, (255, 255, 255), (0, 0, 0))
    textRect = text.get_rect()
    textRect.center = (screen.get_width() // 2, screen.get_height() // 2)
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.TEXTINPUT:
            ID += event.text
        elif event.type == pygame.KEYDOWN:
            key = pygame.key.name(event.key)
            if event.key == pygame.K_j and event.mod == (
                pygame.KMOD_LCTRL | pygame.KMOD_LSHIFT
            ):
                print(ID)
                ID = ""
            elif key == "left":
                pygame.quit()
                sys.exit()
    screen.fill((0, 0, 0))
    screen.blit(text, textRect)
    pygame.display.flip()

```

I had to adapt it a little from the original posted code to use the `TEXTINPUT` event and to use the carriage return keys that the barcode scanner I was using used (CTRL+SHIFT+J). Anyway was able to scan all the barcodes I tried perfectly.

I'm going to close this, as 1) barcode scanning via pygame is a pretty niche application anyway and 2) I cannot reproduce it when using the right sort of event.

**Closed by MyreMylar** 2023-10-30 19:40 UTC
Labels: bug, event
