### ISSUE TITLE
`display.set_icon()` doesn't set the icon in the task bar.

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2090] opened 2023-04-01 13:55 UTC
**Test Code**
```python
import pygame
from pygame.locals import *
import sys

dsf=pygame.display.set_mode((1280,720))
icon=pygame.image.load("peppers3.tif")
pygame.display.set_icon(icon)

while 1:
    for event in pygame.event.get():
        if event.type==QUIT:
            sys.exit()
```
Pygame 1.9.6 (works normally) (cpython 3.7.6)
![image](https://user-images.githubusercontent.com/31395137/229293280-fdfa7e11-a2fc-4919-a200-9a61a324fd5a.png)
Pygame 2.3.0 dev1 (icon didn't changed) (cpython 3.10.6)
![image](https://user-images.githubusercontent.com/31395137/229293320-742ee63c-9cb9-4e88-84ab-c8e1490646c1.png)

**Pygame 2.3.0 dev1 (pypy3.9)**
![image](https://user-images.githubusercontent.com/31395137/229296081-73358964-f675-4711-b8a6-2b766f6a5aaf.png)

**Comment by yunline** [comment] 2023-04-01 14:14
This bug only happens on pygame.
Here is the test code on sdl 2.26.4
```c
#include "SDL.h"

int main(int argc, char* argv[])
{
    SDL_Window *window;
    SDL_Surface *icon;
	SDL_Init(SDL_INIT_VIDEO);

    icon=SDL_LoadBMP("lena.bmp");

    window = SDL_CreateWindow("SDL_WINDOW", 
                       SDL_WINDOWPOS_UNDEFINED, 
                       SDL_WINDOWPOS_UNDEFINED, 
                       640,480,
                       SDL_WINDOW_SHOWN);
    
    SDL_SetWindowIcon(window,icon);

    while(1){
        SDL_Event event;
        SDL_WaitEvent(&event);
        if (event.type==SDL_QUIT)
            break;
    }
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```
Result ↓
![image](https://user-images.githubusercontent.com/31395137/229294423-542669ab-474b-4e85-bcbe-4de6bf6613a8.png)

**Comment by yunline** [comment] 2023-04-01 14:28
This bug may caused by python.
I tested on PySDL2 (SDL 2.26.4 Python 3.10.6) and this bug also appeared.
```python
import sdl2

sdl2.SDL_Init(sdl2.SDL_INIT_VIDEO)

icon=sdl2.SDL_LoadBMP(b"lena.bmp")

win=sdl2.SDL_CreateWindow(b"PySDL2",
    sdl2.SDL_WINDOWPOS_UNDEFINED,
    sdl2.SDL_WINDOWPOS_UNDEFINED,
    640,480,
    sdl2.SDL_WINDOW_SHOWN)

sdl2.SDL_SetWindowIcon(win,icon)

while 1:
    event=sdl2.SDL_Event()
    sdl2.SDL_WaitEvent(event)
    if event.type==sdl2.SDL_QUIT:
        break
```
![image](https://user-images.githubusercontent.com/31395137/229295206-ee0e078d-20c2-4e88-ba8e-83f5bf4aa256.png)

**Comment by Starbuck5** [comment] 2023-04-02 21:51
I didn't remember that it did that in pygame 1.9.6, that's very weird.

I've seen many people ask about this and I've always said that you can't change it (without hacks), because Windows is displaying the icon of the running application. So Windows is displaying the icon of Python.

Of course, when you bundle your app with something like PyInstaller that becomes the running application, so custom icons specified there will show up on the task bar like that.

**Comment by Quantum-HG** [comment] 2023-04-05 13:24
This is not only the case with python but with cpp too.
I made an application with SDL2 2.26.0 and it shows similar results...

![Screenshot](https://user-images.githubusercontent.com/119344859/230093197-958323d4-bb01-4311-b16e-ff4b5a62f290.png)

So maybe this may not be a bug
And yes, the icon on the taskbar is from the icon the "**exe**" file has and not necessarily what has been set for the window

**Comment by Starbuck5** [comment] 2023-05-28 00:57
I'm going to close this as not a bug.

Yunline feel free to reopen if you disagree.

**Closed by Starbuck5** 2023-05-28 00:57 UTC
