### ISSUE TITLE
negative decimal treated differently then positive decimals when moving rect (2623)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1353] opened 2023-02-12 14:40 UTC
#  **Issue &numero;2623 opened by *[cheeze36](https://github.com/cheeze36)* at 2021-06-11 01:07:22**

I noticed a weird bug and I don't know if it in pygame or python. If I try to move rect class by add .1 to the x it doesn't move which is correct cause it expects an integer bit if I try moving it by -.1 it moves -1. <hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2021-06-11 04:22:10*

~~I can't replicate this.~~ Nvm, it just affects the literal `.x`, not the `move` method.

Thanks for the report, but in the future use the issue template!

```py
import pygame

r = pygame.Rect(10,10,20,20) 

r.x += 0.1
print(r) #  <rect(10, 10, 20, 20)>

r.x -= 0.1
print(r) #  <rect(9, 10, 20, 20)>

r.y += 0.1
print(r) #  <rect(9, 10, 20, 20)>

r.y -= 0.1
print(r) #  <rect(9, 9, 20, 20)>
```
<hr>

# # #  **[pradkrish](https://github.com/pradkrish)* commented at 2021-06-18 12:36:23*

isn't that because of rounding down, `int(9.9)` becomes 9 and `int(10.1)` becomes 10. Is this really a bug?
<hr>

# # #  **[CosmicPegasis](https://github.com/CosmicPegasis)* commented at 2021-06-22 05:51:03*

> isn't that because of rounding down, `int(9.9)` becomes 9 and `int(10.1)` becomes 10. Is this really a bug?

I think this is more of a semantics and uniformity thing. Pardon me I'm not that familiar with the source code but if on adding a float > 1 and < 2, if it increments the position by 1, then this behaviour should be allowed, preferably with documentation and vice versa.

That would help people who're new to the library like me I think. 
<hr>

# # #  **[snyntakk404](https://github.com/snyntakk404)* commented at 2021-06-28 21:53:32*

what happens is that they round it. when the rounded result equals 0 they change it to 1 if arg was a positive decimal or -1 if arg was a negative decimal. this isn't a bug. it is phisically impossible to move an object by 0.1 pixel. pixels are what makes up the screen.
EDIT: after looking at a comment with code, i realized that it doesn't move up 1 when it gets moved... this counts as a slight bug i guess?

**Comment by zoldalma999** [comment] 2023-07-29 17:39
I'll close this as intended behaviour, (as we have done before, like in #1269). Plus we have FRect now, if you want small increments, use that or Vectors

**Closed by zoldalma999** 2023-07-29 17:39 UTC
Labels: bug, rect
